version: '3.9'

services:
  app:
    build: .
    ports:
      - 5000:5000
    links:
      - db

  db:
    image: postgres
    ports:
      - 6543:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
